config/routes.rb
Rails.application.routes.draw do
  resources :favorites, only: [:create, :destroy]
  resources :contacts
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :update, :edit, :show, :destroy]
  get 'users/:id/favorites', to: 'users#favorites'
  resources :pictures do
    collection do
      post :confirm
    end
  end
  root to: "sessions#new"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :title, presence: {message: "タイトルを入力してください"}
  validates :content, length: { in: 1..140, message: "内容を１文字以上１４０文字以内で入力してください"}
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :current_user
  before_action :logged_in?
  before_action :authenticate_user
  before_action :check_user, only: [:edit,:update,:destroy]
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  # GET /pictures/new
  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = current_user.pictures.build(picture_params)
    respond_to do |format|
      if @picture.save
        # PictureMailer.picture_mail(@picture).deliver
        format.html { redirect_to pictures_path, notice: '投稿しました' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: "投稿を編集しました" }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: '投稿を削除しました' }
      format.json { head :no_content }
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    @picture.id = params[:id]
    render :new if @picture.invalid?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_picture
    @picture = Picture.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def picture_params
    params.require(:picture).permit(:id, :image, :image_cache,:user_id,:title,:content)
  end

end

app/helpers/pictures_helper.rb
module PicturesHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def confirm_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit' || action_name == 'update'
      #confirm_picture_path(@picture.id)
      picture_path
    end
  end

  def confirm_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit' || action_name == 'update'
      # render confirm_picture_path(@picture.id)
      picture_path
    end
  end

end

app/views/pictures/_form.html.erb
<div class="link">
  <%= form_with(model: picture, local: true, url:confirm_new_or_edit) do |form| %>
    <% if picture.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>
        <ul>
          <% picture.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <table>
      <br>
      <tr>
        <th class="title"><%= form.label :"タイトル" %></th>
        <td class="title"><%= form.text_field :title %></td>
      </tr>
      <tr>
        <th class="content"><%= form.label :"内容" %></th>
        <td class="content"><%= form.text_field :content %></td>
      </tr>
      <tr>
        <th class="image"><%= form.label :"image" %></th>
        <td class="image"><%= form.file_field :image %><% form.hidden_field :image_cache %></td>
      </tr>
    </table>
    <div class="field">
      <% picture.user_id %>
    </div>
    <div class="actions">
      <%= form.submit "投稿する" %>
    </div>
  <% end %>
</div>

app/views/pictures/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @picture, url: confirm_new_or_edit, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <p>タイトル：<%= @picture.title %></p>
  <%= form.hidden_field :content %>
  <p>本文：<%= @picture.content %></p>
  <!-- 確認画面でアップロードした画像を表示させるための記述 -->
  <div class="image">
    <p>imege</p>
    <%= image_tag(@picture.image.url)if @picture.image && @picture.image.url %>
  </div>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :current_user %>
  <%= form.submit "投稿する" %>
  <% end %>
  <%= form_with(model:@picture, url:pictures_path,  local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Pictures</h1>
  <% @pictures.each do |picture| %>
    <div class="post">
      <%= image_tag picture.user.user_image.url, size: '50x50' %>
      <%= picture.user.name %>
      <br>
      <%= picture.title %>
      <br>
      <%= image_tag picture.image.url, size: '614x985'%>
      <br>
      <%= picture.content %>
      <br>
      <%= l(picture.created_at, format: :short)%>
      <!-- <td><%= picture.image %></td> -->
      <br>
      <%= link_to I18n.t("helpers.select.show"), picture %>
      <% if current_user.id == picture.user.id %>
      <%= link_to I18n.t("helpers.submit.edit"), edit_picture_path(picture) %>
      <%= link_to I18n.t("helpers.submit.destroy"), picture, method: :delete, data: { confirm: '本当に削除してもいいですか？' } %>
      <% end %>
      <br>
    </div>
    <br>
    <br>
  <% end %>
  <br>
  <div class="link">
    <%= link_to '新規投稿', new_picture_path %>
  </div>

app/views/pictures/new.html.erb
<h1>New Picture</h1>
  <%= render 'form', picture: @picture %>
  <div class="link">
    <%= link_to 'Back', pictures_path %>
  </div>

app/views/pictures/show.html.erb
<h1>投稿詳細</h1>
  <div class="post">
    <p id="notice"><%= notice %></p>
    <p>投稿者：<%= @picture.user.name %></p>
    <p>タイトル：<%= @picture.title %></p>
    <p>
      <strong>Image:</strong>
      <%= image_tag @picture.image.url, size: '616x985' %>
    </p>
    <p>内容: <%= @picture.content %></p>
    <p>投稿日時：<%= @picture.created_at %></p>

    <%= l(@picture.created_at, format: :short)%>
  </div>
  <div class="link">
    <% unless @picture.user_id == current_user.id %>
      <% if @favorite.present? %>
        <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
      <% end %>
    <% end %>
    <% if current_user.id == @picture.user.id %>
      <%= link_to '編集', edit_picture_path(@picture) %>
      <%= link_to '削除', picture_path, method: :delete, data: { confirm: '本当に削除してもいいですか？' } %>
    <% end %>
    <%= link_to '一覧へ戻る', pictures_path%>
  </div>